// Service Worker for phrakham.life PWA
// Cache version — bump this on each deploy to refresh cached content
var CACHE_VERSION = 'v1-20260305215521';
var CORE_CACHE = 'core-' + CACHE_VERSION;
var RUNTIME_CACHE = 'runtime-' + CACHE_VERSION;

// All pages: auto-generated by Jekyll at build time
var ALL_PAGES = ['/about/','/articles/','/nt/','/','/ot/','/nt/james/','/resources/','/symbols/','/nt/james/3-13-18/','/nt/james/3-1-12/','/nt/james/2-14-26/','/resource/original-language-nuances/','/nt/james/4-11-12/','/nt/james/2-1-13/','/nt/james/1-26-27/','/nt/james/4-1-10/',];

// Core assets: CSS, JS, favicon
var CORE_ASSETS = ALL_PAGES.concat([
  '/assets/css/style.css',
  '/assets/js/dark-mode.js',
  '/assets/js/tooltip.js',
  '/favicon.ico'
]);

// Install: pre-cache core shell
self.addEventListener('install', function(event) {
  event.waitUntil(
    caches.open(CORE_CACHE).then(function(cache) {
      return cache.addAll(CORE_ASSETS);
    }).then(function() {
      return self.skipWaiting();
    })
  );
});

// Activate: clean up old caches
self.addEventListener('activate', function(event) {
  event.waitUntil(
    caches.keys().then(function(keys) {
      return Promise.all(
        keys.filter(function(key) {
          return key !== CORE_CACHE && key !== RUNTIME_CACHE;
        }).map(function(key) {
          return caches.delete(key);
        })
      );
    }).then(function() {
      return self.clients.claim();
    })
  );
});

// Fetch: network-first for HTML, cache-first for assets
self.addEventListener('fetch', function(event) {
  var request = event.request;

  // Only handle GET requests
  if (request.method !== 'GET') return;

  // Skip cross-origin requests except Google Fonts
  var url = new URL(request.url);
  var isGoogleFonts = url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com';
  if (url.origin !== self.location.origin && !isGoogleFonts) return;

  // Google Fonts: cache-first
  if (isGoogleFonts) {
    event.respondWith(
      caches.match(request).then(function(cached) {
        return cached || fetch(request).then(function(response) {
          var clone = response.clone();
          caches.open(RUNTIME_CACHE).then(function(cache) {
            cache.put(request, clone);
          });
          return response;
        });
      })
    );
    return;
  }

  // HTML pages: network-first, fallback to cache
  if (request.headers.get('Accept') && request.headers.get('Accept').includes('text/html')) {
    event.respondWith(
      fetch(request).then(function(response) {
        var clone = response.clone();
        caches.open(RUNTIME_CACHE).then(function(cache) {
          cache.put(request, clone);
        });
        return response;
      }).catch(function() {
        return caches.match(request).then(function(cached) {
          return cached || caches.match('/');
        });
      })
    );
    return;
  }

  // CSS, JS, images, fonts: cache-first
  event.respondWith(
    caches.match(request).then(function(cached) {
      return cached || fetch(request).then(function(response) {
        if (response.ok) {
          var clone = response.clone();
          caches.open(RUNTIME_CACHE).then(function(cache) {
            cache.put(request, clone);
          });
        }
        return response;
      });
    })
  );
});
